version: "3"
services:
  web:
    build: .
    command: python3 server.py
    ports:
      - "80:8080"
    volumes:
      - .:/usr/app/
    depends_on:
      - redis
  redis:
    image: redis
    expose:
      - "6379"
